site:
  title: Payara Community Documentation
  start_page: docs::Overview.adoc
content:
  sources:
    - url: .
      start_path: docs
      branches: HEAD
    - url: .
      start_path: community/docs
      branches: HEAD
asciidoc:
  attributes:
    attribute-missing: 'skip'
    page-site-edition: 'community'
    page-site-edition-capitalised: 'Community'
ui:
  bundle:
    url: https://github.com/payara/antora-ui-default/releases/download/v2.0/ui-bundle.zip
    snapshot: true
runtime:
  fetch: true
output:
    dir: ./build/community/html
